site_name: 中文信息技术开发文档
site_description: 项目文档站点
site_author: L-YLing,烟澪,离烟澪

repo_name: ChineseDevDocs
repo_url: https://github.com/DevApotheosis/ChineseDevDocs
edit_uri: /DevApotheosis/ChineseDevDocs/tree/master/docs/

copyright: Copyright &copy; 2026 DevApotheosis

theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换至暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至亮色模式
  font:
    text: Noto Sans SC
    code: JetBrains Mono
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - meta
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

markdown_extensions:
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - 主页面: 
    - 开始: index.md
    - 第三方库:
      - 语言生态: libs/main.md
    - 系统开发:
      - 概览: os_dev/main.md
      - 引导程序: os_dev/boot/bootloader.md
      - 环境配置: os_dev/dev_os.md
  - 基础教程:
    - 概述: basic/main.md
    - 通用基础: basic/Universal/main.md
  - 贡献指南: contribution.md
  - 导览: guide.md
  - 主史料:
    - 历史页简介: history_langs/history_main.md

extra:
  default_comments: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js